// <auto-generated />
namespace Masonic.Blue.Admin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixchartermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixchartermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201809270229411_fix charter model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
